---
- hosts: servers
  become: yes
  tasks:
  - name: add group tomcat
    group: name=tomcat
  - name: create user tomcat
    user: name=tomcat group=tomcat 
      
  - name: installation of java and tomcat
    yum: 
      name: java-1.8.0-openjdk 
      state: present
  - name: installation of tomcat
    become: yes  
    get_url: 
      url: https://www-eu.apache.org/dist/tomcat/tomcat-8/v8.5.41/bin/apache-tomcat-8.5.41.tar.gz
      dest: /opt/ 
  - name: Unarchive tomcat from download
    unarchive:
      src: /opt/apache-tomcat-8.5.41.tar.gz
      dest: /opt/
      remote_src: yes
  - name: move tomcat directory to tomcat
    command: mv /opt/apache-tomcat-8.5.41 /opt/tomcat
  - name: Starting tomcat
    command: nohup /opt/tomcat/bin/startup.sh
